version: '3.9'
services:
#    sonda:
#        image: sonda
#        build:
#            context: ./
#            dockerfile: Dockerfile
#        ports:
#            - 8080:8080
#        network_mode: bridge
#        depends_on:
#            - database
    database:
        image: 'postgres:latest'
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: sonda

networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.57.0/24