version: '3.9'
services:
    database:
        image: 'postgres:latest'
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: sonda
    sonda:
        build: .
        image: sonda:latest
        ports:
            - "8080:8080"
        depends_on:
            - database

networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.57.0/24